title: Getting My Head Around GitHub
author: Stan Williams
email: swilliams250@dxc.com
description: > # this means to ignore newlines until "baseurl:"
  Going crazy one pull at a time.

# social links
twitter_username: your-twitter-handle
github_username:  swilliamsdxc

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
